location = "local-1"
server_id = [1, 2, 3] # the server to connect to
server_address = ["127.0.0.1:8001", "127.0.0.1:8002", "127.0.0.1:8003"]
summary_filepath = "./logs/coo.json"
output_filepath = "./logs/coo.csv"
client_id = 1

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec =4 
is_write = true
value= "test value 1"
to= 1

[[requests]]
duration_sec =2
is_write = false
value= "test value 2"
to= 2

[[requests]]
duration_sec =1 
is_write = false
value= "test value 3"
to= 3

