cluster_name = "shard1-cluster"
nodes = [1, 2, 3]
node_addrs = ["127.0.0.1:10004", "127.0.0.1:10005", "127.0.0.1:10006"]
initial_leader = 3
initial_flexible_quorum = { read_quorum_size = 2, write_quorum_size = 2 }
